version: "3"

services:
  #   db:
  #     image: postgres:latest
  #     environment:
  #       POSTGRES_USER: postgresuser
  #       POSTGRES_PASSWORD: postgrespassword
  webapi:
    build: .
    # depends_on:
    #   - db
    ports:
      - "5000"
    hostname: xyz
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapi
    ports:
      - "4000:4000"
